/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

/**
 *
 * @author ajai
 */
import javaapplication2.Database.Connect;
import javaapplication2.barcode.GenerateBarcode;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.sql.*;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

public class AddInventory extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form AddProduct
     */
    public AddInventory() throws SQLException {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        updateTable();
        updateLable();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_productqty = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_productid = new javax.swing.JTextField();
        txt_productrate = new javax.swing.JTextField();
        txt_product_hsn = new javax.swing.JTextField();
        txt_product_discount = new javax.swing.JTextField();
        txt_productname = new javax.swing.JTextField();
        txt_category = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        add_product_button = new javax.swing.JButton();
        txt_margin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_CompanyName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_InvoiceNo = new javax.swing.JTextField();
        txt_gst = new javax.swing.JComboBox<>();
        cmd_GenerateBarcode = new javax.swing.JButton();
        cmd_print = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cmd_cancel = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Inventory = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        lab_totalpurchaseprice = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lab_totalmrp = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lab_totalqty = new javax.swing.JLabel();
        cmd_back = new javax.swing.JButton();
        cmd_save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Bar code");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 212, -1, -1));

        jLabel2.setText("Product Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 212, -1, -1));
        getContentPane().add(txt_productqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 232, 60, 25));

        jLabel3.setText("Qty");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 212, 52, -1));
        getContentPane().add(txt_productid, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 232, 62, 25));
        getContentPane().add(txt_productrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 232, 105, 25));
        getContentPane().add(txt_product_hsn, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 232, 97, 25));
        getContentPane().add(txt_product_discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 232, 66, 25));
        getContentPane().add(txt_productname, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 232, 134, 25));
        getContentPane().add(txt_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 232, 114, 25));

        jLabel4.setText("Purchase Price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 212, 105, -1));

        jLabel5.setText("GST(%)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 212, 73, -1));

        jLabel6.setText("Discount");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 212, 66, -1));

        jLabel7.setText("HSN/SAC");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 212, 105, -1));

        jLabel8.setText("Category");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 212, 131, -1));

        add_product_button.setText("ADD");
        add_product_button.setMaximumSize(new java.awt.Dimension(58, 28));
        add_product_button.setMinimumSize(new java.awt.Dimension(58, 28));
        add_product_button.setPreferredSize(new java.awt.Dimension(58, 28));
        add_product_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_product_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(add_product_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1257, 162, -1, -1));
        getContentPane().add(txt_margin, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 232, 80, 24));

        jLabel9.setText("margin");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 212, -1, -1));
        getContentPane().add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(1014, 231, 125, 26));

        jLabel10.setText("Company  Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 123, 203, -1));
        getContentPane().add(txt_CompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 159, 203, -1));

        jLabel11.setText("Invoice No");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 118, -1, -1));
        getContentPane().add(txt_InvoiceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 159, 150, -1));

        txt_gst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "6", "12", "15", "18" }));
        txt_gst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gstActionPerformed(evt);
            }
        });
        getContentPane().add(txt_gst, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 232, -1, 26));

        cmd_GenerateBarcode.setText("Generate Barcode");
        cmd_GenerateBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_GenerateBarcodeActionPerformed(evt);
            }
        });
        getContentPane().add(cmd_GenerateBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(1119, 113, -1, -1));

        cmd_print.setText("Print");
        cmd_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_printActionPerformed(evt);
            }
        });
        getContentPane().add(cmd_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(1257, 113, 58, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 5, -1, -1));

        cmd_cancel.setText("Cancel");
        cmd_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cmd_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1167, 162, -1, -1));

        jLabel12.setText("total");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1022, 212, -1, -1));

        Table_Inventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SI NO", "Date", "Bar Code", "Product Name", "Category", "Qty", "GST(%)", "Purchase Price", "Margin", "HSN/SAC", "Total"
            }
        ));
        jScrollPane1.setViewportView(Table_Inventory);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 264, 1258, 286));

        jLabel13.setText("Total Purchase Price");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 610, -1, -1));

        lab_totalpurchaseprice.setText("0.00");
        getContentPane().add(lab_totalpurchaseprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 610, -1, -1));

        jLabel15.setText("Total Net MRP");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 610, -1, -1));

        lab_totalmrp.setText("0.00");
        getContentPane().add(lab_totalmrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 610, -1, -1));

        jLabel17.setText("Total Qty");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(993, 610, -1, -1));

        lab_totalqty.setText("0");
        getContentPane().add(lab_totalqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(1109, 610, -1, -1));

        cmd_back.setText("Cancel");
        cmd_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_backActionPerformed(evt);
            }
        });
        getContentPane().add(cmd_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1159, 646, -1, -1));

        cmd_save.setText("save");
        cmd_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_saveActionPerformed(evt);
            }
        });
        getContentPane().add(cmd_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(1235, 646, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_product_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_product_buttonActionPerformed
        // TODO add your handling code here:
        try {
            String companyname = txt_CompanyName.getText();
            String invoiceno = txt_InvoiceNo.getText();
            String productid = txt_productid.getText();
            String productname = txt_productname.getText();
            if (productname.equals("")) {
                JOptionPane.showMessageDialog(null, "Enter the product name");
            }
            String category = txt_category.getText();
            int qty = Integer.valueOf(txt_productqty.getText());
            String selectedgst = txt_gst.getSelectedItem().toString();
            double selectedgstd = Double.valueOf(selectedgst);
            double gst = selectedgstd;
            double productprice = Double.valueOf(txt_productrate.getText());
            double margin = Double.valueOf(txt_margin.getText());
            double discount = Double.valueOf(txt_product_discount.getText());
            int hsn = Integer.valueOf(txt_product_hsn.getText());
            double total = (productprice * (gst / 100)) + (productprice / (margin / 100));
            //double total=Double.valueOf(txt_total.getText());
            try {
                Connect.addProduct(companyname, invoiceno, productid, productname, category, qty, gst, productprice, margin, discount, hsn, total);             dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "PROBLEM WITH DB");
            }

        } catch (HeadlessException | NumberFormatException e) {

            JOptionPane.showMessageDialog(null, "Enter the correct values");
        }

//        

    }//GEN-LAST:event_add_product_buttonActionPerformed

    private void txt_gstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gstActionPerformed

    private void cmd_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_printActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("INVENTORY REPORT");
        MessageFormat footer = new MessageFormat("Page(0,number,integer)");
        try {
            Table_Inventory.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (java.awt.print.PrinterException e) {
            JOptionPane.showMessageDialog(null, "No Printer Found");
        }
    }//GEN-LAST:event_cmd_printActionPerformed

    private void cmd_GenerateBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_GenerateBarcodeActionPerformed
        // TODO add your handling code here:
        txt_productid.setText(GenerateBarcode.getCode());
    }//GEN-LAST:event_cmd_GenerateBarcodeActionPerformed

    private void cmd_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_cancelActionPerformed
        // TODO add your handling code here:
        txt_CompanyName.setText("");
        txt_InvoiceNo.setText("");
        txt_category.setText("");
        txt_margin.setText("");
        txt_product_discount.setText("");
        txt_product_hsn.setText("");
        txt_productid.setText("");
        txt_productname.setText("");
        txt_productqty.setText("");
        txt_productrate.setText("");
        txt_total.setText("");

    }//GEN-LAST:event_cmd_cancelActionPerformed

    private void cmd_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_saveActionPerformed
        try {
            // TODO add your handling code here:
            updateLable();
            updateTable();
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(AddInventory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmd_saveActionPerformed

    private void cmd_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_backActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cmd_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public  void updateTable() {

        ResultSet rs = Connect.getInventoryTable();
        Table_Inventory.setModel(DbUtils.resultSetToTableModel(rs));

    }
    
    public  void updateLable() throws SQLException{
        lab_totalqty.setText(Connect.getTotalQty());
        lab_totalpurchaseprice.setText(Connect.getTotalPurchasePrice());
        lab_totalmrp.setText(Connect.getNetMRP());
    }

    public static void main(String args[]) throws SQLException {
        AddInventory i  = new AddInventory();
        i.updateTable();
       // i.updateLable();

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddInventory().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AddInventory.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Inventory;
    private javax.swing.JButton add_product_button;
    private javax.swing.JButton cmd_GenerateBarcode;
    private javax.swing.JButton cmd_back;
    private javax.swing.JButton cmd_cancel;
    private javax.swing.JButton cmd_print;
    private javax.swing.JButton cmd_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab_totalmrp;
    private javax.swing.JLabel lab_totalpurchaseprice;
    private javax.swing.JLabel lab_totalqty;
    private javax.swing.JTextField txt_CompanyName;
    private javax.swing.JTextField txt_InvoiceNo;
    private javax.swing.JTextField txt_category;
    private javax.swing.JComboBox<String> txt_gst;
    private javax.swing.JTextField txt_margin;
    private javax.swing.JTextField txt_product_discount;
    private javax.swing.JTextField txt_product_hsn;
    private javax.swing.JTextField txt_productid;
    private javax.swing.JTextField txt_productname;
    private javax.swing.JTextField txt_productqty;
    private javax.swing.JTextField txt_productrate;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
